config/routes.rb
AnimalHouse::Application.routes.draw do
  resources :follows

  resources :vetxespecialidades

  resources :pathoxracas

  resources :pathoxtratamentos

  resources :pathoxsintomas

  resources :itemlinks

  resources :relatos

  resources :patologias

  resources :patologia

  resources :especialidades

  resources :tratamentos

  resources :sintomas

  resources :racas

  resources :animals

  resources :edicaos

  resources :veterinarios

  resources :items

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :item
end

app/models/edicao.rb
class Edicao < ActiveRecord::Base
  belongs_to :veterinario
  belongs_to :item
end

app/models/especialidade.rb
class Especialidade < ActiveRecord::Base
  belongs_to :item
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower , :class_name => 'Veterinario' , :foreign_key => 'follower_id' 
  belongs_to :followed , :class_name => 'Vetertinario' , :foreign_key => 'followed_id'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :veterinario
end

app/models/itemlink.rb
class Itemlink < ActiveRecord::Base
  belongs_to :veterinario
end

app/models/pathoxraca.rb
class Pathoxraca < ActiveRecord::Base
  belongs_to :itemlink
  belongs_to :patologia
  belongs_to :raca
end

app/models/pathoxsintoma.rb
class Pathoxsintoma < ActiveRecord::Base
  belongs_to :itemlink
  belongs_to :patologia
  belongs_to :sintoma
end

app/models/patologia.rb
class Patologia < ActiveRecord::Base
  belongs_to :especialidade
  belongs_to :item
end

app/models/patologium.rb
class Patologium < ActiveRecord::Base
  belongs_to :item
  belongs_to :especialidade
end

app/models/raca.rb
class Raca < ActiveRecord::Base
  belongs_to :animal
  belongs_to :item
end

app/models/relato.rb
class Relato < ActiveRecord::Base
  belongs_to :item
  belongs_to :patologia
end

app/models/sintoma.rb
class Sintoma < ActiveRecord::Base
  belongs_to :item
end

app/models/tratamento.rb
class Tratamento < ActiveRecord::Base
  belongs_to :item
end

app/models/veterinario.rb
class Veterinario < ActiveRecord::Base
end

app/controllers/edicaos_controller.rb
class EdicaosController < InheritedResources::Base
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/edicaos_helper.rb
module EdicaosHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/racas_helper.rb
module RacasHelper
end

app/helpers/relatos_helper.rb
module RelatosHelper
end

app/helpers/sintomas_helper.rb
module SintomasHelper
end

app/views/edicaos/_form.html.haml
= semantic_form_for(@item) do |f| 
  = f.input :camposEditado, :label => 'CampoEditado'
  = f.input :status, :label => 'Status'
  = f.input :item, :member_label => :id, :label => 'Item'
  = f.input :veterinario, :member_label => :nome, :label => 'Veterinario'
  = f.submit 'Salvar'

app/views/edicaos/edit.html.erb
<h1>Editing edicao</h1>

<%= render 'form' %>

<%= link_to 'Show', @edicao %> |
<%= link_to 'Back', edicaos_path %>

app/views/edicaos/index.html.erb
<h1>Listing edicaos</h1>

<table>
  <tr>
    <th>Status</th>
    <th>CampoEditado</th>
    <th>Veterinario</th>
    <th>Item</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @edicaos.each do |edicao| %>
  <tr>
    <td><%= edicao.status %></td>
    <td><%= edicao.camposEditado %></td>
    <td><%= edicao.veterinario.nome %></td>
    <td><%= edicao.item.id %></td>
    <td><%= link_to 'Show', edicao %></td>
    <td><%= link_to 'Edit', edit_edicao_path(edicao) %></td>
    <td><%= link_to 'Excluir', edicao, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Edicao', new_edicao_path %>

app/views/edicaos/new.html.erb
<h1>New edicao</h1>

<%= render 'form' %>

<%= link_to 'Back', edicaos_path %>

app/views/edicaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @edicao.status %>
</p>

<p>
  <b>CampoEditado:</b>
  <%= @edicao.camposEditado %>
</p>

<p>
  <b>Veterinario:</b>
  <%= @edicao.veterinario.nome %>
</p>

<p>
  <b>Item:</b>
  <%= @edicao.item.id %>
</p>


<%= link_to 'Edit', edit_edicao_path(@edicao) %> |
<%= link_to 'Back', edicaos_path %>