config/routes.rb
AnimalHouse::Application.routes.draw do
  resources :follows

  resources :vetxespecialidades

  resources :pathoxracas

  resources :pathoxtratamentos

  resources :pathoxsintomas

  resources :itemlinks

  resources :relatos

  resources :patologias

  resources :patologia

  resources :especialidades

  resources :tratamentos

  resources :sintomas

  resources :racas

  resources :animals

  resources :edicaos

  resources :veterinarios

  resources :items

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :item
end

app/models/edicao.rb
class Edicao < ActiveRecord::Base
  belongs_to :veterinario
  belongs_to :item
end

app/models/especialidade.rb
class Especialidade < ActiveRecord::Base
  belongs_to :item
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower , :class_name => 'Veterinario' , :foreign_key => 'follower_id' 
  belongs_to :followed , :class_name => 'Vetertinario' , :foreign_key => 'followed_id'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :veterinario
end

app/models/itemlink.rb
class Itemlink < ActiveRecord::Base
  belongs_to :veterinario
end

app/models/pathoxraca.rb
class Pathoxraca < ActiveRecord::Base
  belongs_to :itemlink
  belongs_to :patologia
  belongs_to :raca
end

app/models/pathoxsintoma.rb
class Pathoxsintoma < ActiveRecord::Base
  belongs_to :itemlink
  belongs_to :patologia
  belongs_to :sintoma
end

app/models/patologia.rb
class Patologia < ActiveRecord::Base
  belongs_to :especialidade
  belongs_to :item
end

app/models/patologium.rb
class Patologium < ActiveRecord::Base
  belongs_to :item
  belongs_to :especialidade
end

app/models/raca.rb
class Raca < ActiveRecord::Base
  belongs_to :animal
  belongs_to :item
end

app/models/relato.rb
class Relato < ActiveRecord::Base
  belongs_to :item
  belongs_to :patologia
end

app/models/sintoma.rb
class Sintoma < ActiveRecord::Base
  belongs_to :item
end

app/models/tratamento.rb
class Tratamento < ActiveRecord::Base
  belongs_to :item
end

app/models/veterinario.rb
class Veterinario < ActiveRecord::Base
end

app/controllers/especialidades_controller.rb
class EspecialidadesController < InheritedResources::Base
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/edicaos_helper.rb
module EdicaosHelper
end

app/helpers/especialidades_helper.rb
module EspecialidadesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/racas_helper.rb
module RacasHelper
end

app/helpers/relatos_helper.rb
module RelatosHelper
end

app/views/especialidades/_form.html.haml
= semantic_form_for(@especialidade) do |f| 
  = f.input :nome, :label => 'Nome'
  = f.input :detalhes, :label => 'Detalhes'
  = f.input :item, :member_label => :id, :label => 'Item'
  = f.submit 'Salvar'

app/views/especialidades/edit.html.erb
<h1>Editing especialidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @especialidade %> |
<%= link_to 'Back', especialidades_path %>

app/views/especialidades/index.html.erb
<h1>Listing especialidades</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Detalhes</th>
    <th>Item</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @especialidades.each do |especialidade| %>
  <tr>
    <td><%= especialidade.nome %></td>
    <td><%= especialidade.detalhes %></td>
    <td><%= especialidade.item.id %></td>
    <td><%= link_to 'Show', especialidade %></td>
    <td><%= link_to 'Edit', edit_especialidade_path(especialidade) %></td>
    <td><%= link_to 'Excluir', especialidade, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Especialidade', new_especialidade_path %>

app/views/especialidades/new.html.erb
<h1>New especialidade</h1>

<%= render 'form' %>

<%= link_to 'Back', especialidades_path %>

app/views/especialidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @especialidade.nome %>
</p>

<p>
  <b>Detalhes:</b>
  <%= @especialidade.detalhes %>
</p>

<p>
  <b>Item:</b>
  <%= @especialidade.item.id %>
</p>


<%= link_to 'Edit', edit_especialidade_path(@especialidade) %> |
<%= link_to 'Back', especialidades_path %>