config/routes.rb
AnimalHouse::Application.routes.draw do
  resources :follows

  resources :vetxespecialidades

  resources :pathoxracas

  resources :pathoxtratamentos

  resources :pathoxsintomas

  resources :itemlinks

  resources :relatos

  resources :patologias

  resources :patologia

  resources :especialidades

  resources :tratamentos

  resources :sintomas

  resources :racas

  resources :animals

  resources :edicaos

  resources :veterinarios

  resources :items

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :item
end

app/models/edicao.rb
class Edicao < ActiveRecord::Base
  belongs_to :veterinario
  belongs_to :item
end

app/models/especialidade.rb
class Especialidade < ActiveRecord::Base
  belongs_to :item
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower , :class_name => 'Veterinario' , :foreign_key => 'follower_id' 
  belongs_to :followed , :class_name => 'Vetertinario' , :foreign_key => 'followed_id'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :veterinario
end

app/models/itemlink.rb
class Itemlink < ActiveRecord::Base
  belongs_to :veterinario
end

app/models/pathoxraca.rb
class Pathoxraca < ActiveRecord::Base
  belongs_to :itemlink
  belongs_to :patologia
  belongs_to :raca
end

app/models/pathoxsintoma.rb
class Pathoxsintoma < ActiveRecord::Base
  belongs_to :itemlink
  belongs_to :patologia
  belongs_to :sintoma
end

app/models/patologia.rb
class Patologia < ActiveRecord::Base
  belongs_to :especialidade
  belongs_to :item
end

app/models/patologium.rb
class Patologium < ActiveRecord::Base
  belongs_to :item
  belongs_to :especialidade
end

app/models/raca.rb
class Raca < ActiveRecord::Base
  belongs_to :animal
  belongs_to :item
end

app/models/relato.rb
class Relato < ActiveRecord::Base
  belongs_to :item
  belongs_to :patologia
end

app/models/sintoma.rb
class Sintoma < ActiveRecord::Base
  belongs_to :item
end

app/models/tratamento.rb
class Tratamento < ActiveRecord::Base
  belongs_to :item
end

app/models/veterinario.rb
class Veterinario < ActiveRecord::Base
end

app/controllers/pathoxracas_controller.rb
class PathoxracasController < InheritedResources::Base
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/edicaos_helper.rb
module EdicaosHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pathoxracas_helper.rb
module PathoxracasHelper
end

app/helpers/racas_helper.rb
module RacasHelper
end

app/helpers/relatos_helper.rb
module RelatosHelper
end

app/views/pathoxracas/_form.html.haml
= semantic_form_for(@pathoxraca) do |f| 
  = f.input :patologia, :member_label => :nome, :label => 'Patologia'
  = f.input :raca, :member_label => :nome, :label => 'Raca'
  = f.input :itemlink, :member_label => :id, :label => 'Itemlink'
  = f.submit 'Salvar'

app/views/pathoxracas/edit.html.erb
<h1>Editing pathoxraca</h1>

<%= render 'form' %>

<%= link_to 'Show', @pathoxraca %> |
<%= link_to 'Back', pathoxracas_path %>

app/views/pathoxracas/index.html.erb
<h1>Listing pathoxracas</h1>

<table>
  <tr>
    <th>Itemlink</th>
    <th>Patologia</th>
    <th>Raca</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pathoxracas.each do |pathoxraca| %>
  <tr>
    <td><%= pathoxraca.itemlink.id %></td>
    <td><%= pathoxraca.patologia.nome %></td>
    <td><%= pathoxraca.raca.nome %></td>
    <td><%= link_to 'Show', pathoxraca %></td>
    <td><%= link_to 'Edit', edit_pathoxraca_path(pathoxraca) %></td>
    <td><%= link_to 'Excluir', pathoxraca, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pathoxraca', new_pathoxraca_path %>

app/views/pathoxracas/new.html.erb
<h1>New pathoxraca</h1>

<%= render 'form' %>

<%= link_to 'Back', pathoxracas_path %>

app/views/pathoxracas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Itemlink:</b>
  <%= @pathoxraca.itemlink.id %>
</p>

<p>
  <b>Patologia:</b>
  <%= @pathoxraca.patologia.nome %>
</p>

<p>
  <b>Raca:</b>
  <%= @pathoxraca.raca.nome %>
</p>


<%= link_to 'Edit', edit_pathoxraca_path(@pathoxraca) %> |
<%= link_to 'Back', pathoxracas_path %>